API_Desafio.API/Models/EditUserRequest.cs
using API_Desafio.Domain.Models;

namespace API_Desafio.API.Models;

public class EditUserRequest
{
    public Guid Id { get; set; }
    public string Username { get; set; } = null!;
    public string DocumentNumber { get; set; } = null!;
    public DateTime DateOfBirth { get; set; }
    public string First { get; set; } = null!;
    public string Last { get; set; } = null!;
    public string Thumbnail { get; set; } = null!;

    public static EditUserRequest CreateFromUser(User user)
    {
        return new EditUserRequest
        {
            Id = user.Id,
            Username = user.LoginInformation.Username,
            DocumentNumber = user.DocumentInformation.Number,
            DateOfBirth = user.DateOfBirthInformation.DateOfBirth,
            First = user.NameInformation.First,
            Last = user.NameInformation.Last,
            Thumbnail = user.ImageInformation.Thumbnail
        };
    }
}

API_Desafio.API/Models/ErrorViewModel.cs
namespace API_Desafio.API.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }
    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

API_Desafio.API/Controllers/AuthController.cs
using API_Desafio.Application.Dtos;
using API_Desafio.Application.Services;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Mvc;
using System.IdentityModel.Tokens.Jwt;
using System.Security.Claims;

namespace API_Desafio.API.Controllers;
public class AuthController : Controller
{
    public const string HOME_CONTROLLER = "Home";
    private readonly IAuthService _authenticationService;
    private readonly ITokenProvider _tokenProvider;

    public AuthController(IAuthService authenticationService, ITokenProvider tokenProvider)
    {
        _authenticationService = authenticationService;
        _tokenProvider = tokenProvider;
    }

    [HttpGet]
    public IActionResult Login()
    {
        LoginRequestDto loginRequestDto = new();

        if (string.IsNullOrEmpty(_tokenProvider.GetToken()))
        {
            return View(loginRequestDto);
        }
        else
        {
            TempData["error"] = $"You are already logged in.";
            return RedirectToAction(nameof(Index), HOME_CONTROLLER);
        }
    }

    [HttpPost]
    public async Task<IActionResult> Login(LoginRequestDto loginRequestDto)
    {
        var loginResult = await _authenticationService.LoginAsync(loginRequestDto);

        if (!string.IsNullOrEmpty(loginResult.Token))
        {
            _tokenProvider.SetToken(loginResult.Token!);
            await SignInUserAsync(loginResult);
            return RedirectToAction(nameof(Index), HOME_CONTROLLER);
        }
        else
        {
            TempData["error"] = $"Email or Password not valid.";
            return View(loginRequestDto);
        }
    }

    public async Task<IActionResult> Logout()
    {
        await HttpContext.SignOutAsync();
        _tokenProvider.ClearToken();
        return RedirectToAction(nameof(Index), HOME_CONTROLLER);
    }

    private async Task SignInUserAsync(LoginResponseDto loginResponseDto)
    {
        var handler = new JwtSecurityTokenHandler();
        var token = handler.ReadJwtToken(loginResponseDto.Token);
        var identity = new ClaimsIdentity(CookieAuthenticationDefaults.AuthenticationScheme);

        identity.AddClaim(new Claim(JwtRegisteredClaimNames.Sub, token.Claims.FirstOrDefault(t => t.Type == JwtRegisteredClaimNames.Sub).Value));
        identity.AddClaim(new Claim(JwtRegisteredClaimNames.Email, token.Claims.FirstOrDefault(t => t.Type == JwtRegisteredClaimNames.Email).Value));
        identity.AddClaim(new Claim(JwtRegisteredClaimNames.Name, token.Claims.FirstOrDefault(t => t.Type == JwtRegisteredClaimNames.Name).Value));


        var principal = new ClaimsPrincipal(identity);
        await HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme, principal);
    }
}

API_Desafio.API/Controllers/HomeController.cs
using API_Desafio.API.Models;
using API_Desafio.ApplicationServices.Dtos;
using API_Desafio.ApplicationServices.Users;
using API_Desafio.Infrastructure.Data;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Diagnostics;

namespace API_Desafio.API.Controllers;

public class HomeController : Controller
{
    private readonly IRandomUserGeneratorAPIService _randomUserGeneratorService;
    private readonly ApplicationDbContext _ctx;
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger, IRandomUserGeneratorAPIService randomUserGeneratorService, ApplicationDbContext ctx)
    {
        _logger = logger;
        _randomUserGeneratorService = randomUserGeneratorService;
        _ctx = ctx;
    }

    [Authorize]
    public async Task<IActionResult> Index()
    {
        var users = await _ctx.User.ToListAsync();

        List<UserDto> usersReturnList = new();
        foreach (var user in users)
        {
            usersReturnList.Add(UserDto.CreateFromUser(user));
        }

        return View(usersReturnList.OrderBy(u => u.Name).ThenBy(u => u.Email));
    }

    public IActionResult Privacy()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }

    public IActionResult Edit()
    {
        return View();
    }
}

API_Desafio.API/Controllers/UserController.cs
using API_Desafio.API.Models;
using API_Desafio.Infrastructure.Data;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace API_Desafio.API.Controllers;

public class UserController : Controller
{
    public const string REDIRECT_TO_HOME = "Home";

    private readonly ApplicationDbContext _ctx;
    private readonly ILogger<UserController> _logger;

    public UserController(ApplicationDbContext ctx, ILogger<UserController> logger)
    {
        _ctx = ctx;
        _logger = logger;
    }

    [Authorize]
    public async Task<IActionResult> EditUser(Guid userId)
    {
        if (ModelState.IsValid)
        {
            var user = await _ctx.User.FirstOrDefaultAsync(u => u.Id == userId);
            if (user is not null)
            {
                return View(EditUserRequest.CreateFromUser(user));
            }
        }

        TempData["error"] = $"Could not find the user with id {userId}";
        return NotFound();
    }

    [Authorize]
    [HttpPost]
    public async Task<IActionResult> EditUser(EditUserRequest model)
    {
        try
        {
            if (ModelState.IsValid)
            {
                var user = await _ctx.User.FirstOrDefaultAsync(u => u.Id == model.Id);
                if (user is null)
                {
                    TempData["error"] = $"Could not find the user with id {model.Id}";
                    return RedirectToAction(nameof(Index));
                }

                user.Update(
                    model.Username,
                    model.DocumentNumber,
                    model.DateOfBirth,
                    model.First,
                    model.Last,
                    model.Thumbnail);

                await _ctx.SaveChangesAsync();
                TempData["success"] = "User edited successfully";
                return RedirectToAction(nameof(Index), REDIRECT_TO_HOME);
            }

            TempData["error"] = "Error updating user";
            return View(model);
        }
        catch (Exception ex)
        {
            _logger.LogError("{0} - {1}", ex.Message, ex.InnerException);
            TempData["error"] = "Error updating user";
            return View(model);

        }
    }
}

API_Desafio.API/Views/Home/Index.cshtml
@using API_Desafio.Application.Services
@using API_Desafio.ApplicationServices.Dtos
@inject ITokenProvider tokenProvider

@model IEnumerable<UserDto>

@{
    ViewData["Title"] = "API Desafio";
}

@if (!string.IsNullOrEmpty(tokenProvider.GetToken()))
{
    <div class="card shadow border-0 mt-4">
        <div class="card-header bg-secondary bg-gradient ml-0 py-3">
            <div class="row">
                <div class="col-12 text-center">
                    <h1 class="text-white">List of Users</h1>
                </div>
            </div>
        </div>
        <div class="card-body p-4">
            <div class="row pb-3">
                <div class="col-6">
                </div>
            </div>
            <table class="table">
                <thead>
                    <tr>
                        <th> Username </th>
                        <th> Email </th>
                        <th> Name </th>
                        <th> Age </th>
                        <th> Date of Birth </th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td> @item.Username </td>
                            <td> @item.Email </td>
                            <td> @item.Name </td>
                            <td> @item.DateOfBirthInformation.Age</td>
                            <td> @item.DateOfBirthInformation.DateOfBirth.Date</td>
                            <td>
                                <a class="btn btn-success" asp-controller="User" asp-action="EditUser" asp-route-userId="@item.Id">
                                    <i class="bi bi-pencil-square"></i>
                                </a>
                            </td>
                            <td></td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
}
else
{
    <h1>Please Login First in Order to See the Users...</h1>
}


@section Scripts {
    <partial name="_Notifications" />
}

API_Desafio.API/Views/Shared/_Layout.cshtml
@using API_Desafio.Application.Services
@inject ITokenProvider tokenProvider

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - API Desafio</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/API_Desafio.API.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.css" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">API Desafio</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-2">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        @if (!string.IsNullOrEmpty(tokenProvider.GetToken()))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Auth" asp-action="Logout">Logout</a>
                            </li>
                        }
                        else
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Auth" asp-action="Login">Login</a>
                            </li>
                        }

                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container"> &copy; 2024 - API Desafio - Lucas Rodrigues Castelo Branco</div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/2.1.4/toastr.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

API_Desafio.API/Views/Shared/_Notifications.cshtml
@if (TempData["error"] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/2.1.4/toastr.min.js"></script>
    <script type="text/javascript">
        toastr.error('@TempData["error"]');
    </script>
}

@if (TempData["success"] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/2.1.4/toastr.min.js"></script>
    <script type="text/javascript">
        toastr.success('@TempData["success"]');
    </script>
}

API_Desafio.API/Views/User/EditUser.cshtml
@model EditUserRequest

<form asp-action="EditUser" enctype="multipart/form-data">
    <br />
    <div class="container border p-3">
        <h1 class="text-white text-center">Edit User</h1>
        <hr />
        <input asp-for="Id" hidden />

        <div class="row">
            <div class="col-10">
                <div class="row">
                    <div class="col-2">
                        <label class="control-label pt-2" style="font-size:20px;">Firstname</label>
                    </div>
                    <div class="col-10 pb-3">
                        <input class="form-control" asp-for="First" />
                        <span asp-validation-for="First" class="text-danger"></span>
                    </div>
                    <div class="col-2">
                        <label class="control-label pt-2" style="font-size:20px;">Lastname</label>
                    </div>
                    <div class="col-10 pb-3">
                        <input class="form-control" asp-for="Last" />
                        <span asp-validation-for="Last" class="text-danger"></span>
                    </div>
                    <div class="col-2">
                        <label class="control-label pt-2" style="font-size:20px;">Username</label>
                    </div>
                    <div class="col-10 pb-3">
                        <input class="form-control" asp-for="Username" />
                        <span asp-validation-for="Username" class="text-danger"></span>
                    </div>
                    <div class="col-2">
                        <label class="control-label pt-2" style="font-size:20px;">DocumentNumber</label>
                    </div>
                    <div class="col-10 pb-3">
                        <input class="form-control" asp-for="DocumentNumber" />
                        <span asp-validation-for="DocumentNumber" class="text-danger"></span>
                    </div>
                    <div class="col-2">
                        <label class="control-label pt-2" style="font-size:20px;">DateOfBirth</label>
                    </div>
                    <div class="col-10 pb-3">
                        <input class="form-control" rows="5" asp-for="DateOfBirth" type="date">
                    </div>
                    <div class="col-2">
                        <label class="control-label pt-2" style="font-size:20px;">Thumbnail</label>
                    </div>
                    <div class="col-10 pb-3">
                        <input class="form-control" rows="5" asp-for="Thumbnail">
                    </div>

                    <div class="col-16">
                        <input type="submit" value="Edit" class="btn btn-success form-control" />
                    </div>
                </div>
            </div>
            <div class="col-2">
                <img src="@Model.Thumbnail" class="w-100" alt="The User Thumbnail" />
            </div>
        </div>
    </div>
</form>

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
    <partial name="_Notifications" />
}